working with mlflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,63 +1,63 @@
-name: CI Pipeline
+# name: CI Pipeline
 
-on:
-  push:
+# on:
+#   push:
 
 
-jobs:
-  integration:
-    name: Continuous Integration
-    runs-on: ubuntu-latest
+# jobs:
+#   integration:
+#     name: Continuous Integration
+#     runs-on: ubuntu-latest
 
-    steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v4
+#     steps:
+#     - name: Checkout Repository
+#       uses: actions/checkout@v4
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.12
+#     - name: Set up Python
+#       uses: actions/setup-python@v5
+#       with:
+#         python-version: 3.12
 
-    - name: Install Dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+#     - name: Install Dependencies
+#       run: |
+#         python -m pip install --upgrade pip
+#         pip install -r requirements.txt
 
-    - name: Run app and Test
-      run: |
-        # 1. Start the app in the background (&)
-        python app.py & 
+#     - name: Run app and Test
+#       run: |
+#         # 1. Start the app in the background (&)
+#         python app.py & 
         
-        # 2. Wait for the server to boot up
-        sleep 5 
+#         # 2. Wait for the server to boot up
+#         sleep 5 
         
-        # 3. Test if the app is alive (Health Check)
-        curl --fail http://127.0.0.1:8000 || exit 1
+#         # 3. Test if the app is alive (Health Check)
+#         curl --fail http://127.0.0.1:8000 || exit 1
         
-        # 4. Kill the background process so the CI can finish
-        pkill python
+#         # 4. Kill the background process so the CI can finish
+#         pkill python
     
-  run-using-docker:
-      name: Docker CI
-      needs: integration
-      runs-on: ubuntu-latest
+#   run-using-docker:
+#       name: Docker CI
+#       needs: integration
+#       runs-on: ubuntu-latest
       
 
-      steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v4
+#       steps:
+#         - name: Checkout Repository
+#           uses: actions/checkout@v4
           
-        - name: Login to Docker Hub
-          uses: docker/login-action@v3
-          with:
-            username: ${{ secrets.DOCKER_USERNAME }}
-            password: ${{ secrets.DOCKER_PASSWORD }}
+#         - name: Login to Docker Hub
+#           uses: docker/login-action@v3
+#           with:
+#             username: ${{ secrets.DOCKER_USERNAME }}
+#             password: ${{ secrets.DOCKER_PASSWORD }}
 
-        - name: Build and Push
-          uses: docker/build-push-action@v5
-          with:
-            push: true
-            tags: midhun256/carpred:latest
+#         - name: Build and Push
+#           uses: docker/build-push-action@v5
+#           with:
+#             push: true
+#             tags: midhun256/carpred:latest
 
     
   # build-and-push-ecr-image:
